language: node_js

matrix:
  include:
    - os: linux
      node_js: "8"

# can't run all of them because it's gonna work in parallel using the same api

#    - os: linux
#      node_js: "7"
#    - os: linux
#      node_js: "6"
#    - os: linux
#      node_js: "4.3"
#
#    - os: osx
#      node_js: "8"
#    - os: osx
#      node_js: "7"
#    - os: osx
#      node_js: "6"
#    - os: osx
#      node_js: "4.3"

before_script:
  - openssl aes-256-cbc -K $encrypted_11052799cf5f_key -iv $encrypted_11052799cf5f_iv -in app.config.js.enc -out react/app.config.js -d

script:
  - yarn test
